### ISSUE TITLE
Missing git as a project dependency

### ISSUE THREAD

**Issue by alejandrosame** [OpenMined/syft#455]
## Description
On a fresh Ubuntu installation, the SyftBox installer installs the client, which then fails to run the `starter_app`. The logs indicate that `subprocess` couldn't find `git`.

## How to Reproduce
For example, using distrobox to manage containers:
1. Create an Ubuntu container with `distrobox create --name test-install --image ubuntu:latest`.
2. Enter the container with `distrobox enter daysflchallenge`.
3. Inside the container run the installer with `curl -LsSf https://syftbox.openmined.org/install.sh | sh`.
4. Follow the instructions with the command prompt.
5. Eventually, the message `ERROR    | syftbox.client.plugins.apps:run_app:351 - Error calling subprocess for api 'starter_app` is displayed in the command line.

## Expected Behavior
The install script detects that git is missing and installs it. Alternatively, it preemptively tells the user that the dependency is missing.

**Comment by eelcovdw** [comment]
Fixed by #458
